#!/usr/bin/env python3

import sys

from src.aes_class import run_my_aes

def usage():
    print("USAGE:")
    print("    ./my_aes [OPTIONS]")
    print("\nOPTIONS:")
    print("    -h, --help    Display this help message")
    print("    -e            Encrypt a file")
    print("    -d            Decrypt a file")
    print("    -k            Key to use for encryption/decryption (128 bits key)")
    print("    -i            Input file to encrypt/decrypt")
    print("\nKEY (128-bits):")
    print("    The key could be a string of 16 characters")
    print("  OR")
    print("    The key could be a valid 32 characters hexadecimal string")




def main():
    if "-h" in sys.argv or "--help" in sys.argv:
        usage()
        return 0
    res = run_my_aes(sys.argv[1:])  
    return res

if __name__ == '__main__':
    sys.exit(main())
